# Generated by Django 5.0.3 on 2024-03-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_secservicemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secservicemodel',
            name='end_time',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='secservicemodel',
            name='start_time',
            field=models.BigIntegerField(),
        ),
    ]
