# Generated by Django 5.0.3 on 2024-04-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_alter_secservicemodel_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secservicemodel',
            name='number_of_copy',
            field=models.IntegerField(default=0),
        ),
    ]
